### ISSUE TITLE
User Manual doesn't match with current cli_dispatch commands

### ISSUE THREAD

**Issue by peterkraume** [b13/t3ext-dam_falmigration#42]
This is the current list of cli_dispatch commands:
- dammigration:migratedamrecords
- dammigration:migratedammetadata
- dammigration:migratemediatagsinrte
- dammigration:migratedamcategories
- dammigration:migratedamcategoriestofalcollections
- dammigration:migratecategoryrelations
- dammigration:migratedamfrontendplugins
- dammigration:cleanupduplicatefalcollectionreferences
- dammigration:updatereferenceindex
- dammigration:migraterelations
- dammigration:migrateselections
- dammigration:migratedamttnews

But in the User Manual doesn't reflect this and contains mismatches like dammigration:connectdamrecordswithsysfile

**Comment by ursbraem** [comment]
Hi Michiel
sorry for the no-response, I haven't continued work on said project yet. When I'll encounter it again, I'll open the separate ticket. By the way, and off topic: THANK YOU for this extension (which has flawlessly worked on another site for me) and for nc_staticfilecache (without it, we literally couldn't run TYPO3 on our shared hostings!)
Cheers
Urs
