### ISSUE TITLE
dammigration:migraterelations > order by in execSelectDamReferencesWhereSysFileExists

### ISSUE THREAD

**Issue by arpi68** [b13/t3ext-dam_falmigration#63]
Function execSelectDamReferencesWhereSysFileExists orders records by field tx_dam_mm_ref.sorting.
In my case, I had 7 records with sorting=0, but sorting_foreign was filled with 1 to 7.
The migration resulted in mixing up images and their captions.

tx_dam_mm_ref.sorting_foreign sould be at least the 2nd order by-Parameter

return $this->database->exec_SELECTquery(
                'tx_dam_mm_ref.*,
			sys_file_metadata.title,
			sys_file_metadata.description,
			sys_file_metadata.alternative,
			sys_file.uid as sys_file_uid',
                'tx_dam_mm_ref
			JOIN sys_file ON
				sys_file._migrateddamuid = tx_dam_mm_ref.uid_local
			JOIN sys_file_metadata ON
				sys_file.uid = sys_file_metadata.file
				',
                $where,
                '',
                'tx_dam_mm_ref.sorting ASC,tx_dam_mm_ref.sorting_foreign ASC',
                (int)$this->getRecordLimit()
        );

Cheers
Roland

**Comment by Tuurlijk** [comment]
Nice catch. Can you provide a pull request?

**Comment by Tuurlijk** [comment]
Thanks Roland
